name: Docker CD

on:
  pull_request:
    types:
     - closed
    branches:
     - main
  
jobs:
  Build_and_deploy:
    runs-on: self-hosted
    steps:  
      - uses: actions/checkout@v3
      - name: Rebuild posting service
        run: |
          docker build . --tag auth-service
          docker stop auth-service
          docker remove auth-service
          docker run -d --rm -it -p 8081:8080 --name auth-service auth
