name: Docker CD

on:
  pull_request:
    types:
     - closed
    branches:
     - main
  
jobs:
  Build_and_deploy:
    runs-on: self-hosted
    steps:  
      - uses: actions/checkout@v3
      - name: Rebuild posting service
        run: |
          docker build . --tag auth-service
          docker stop auth-service
          docker remove auth-service
          docker run -d --rm -it -p 8081:80 -p 8082:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORTS=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="<CREDENTIAL_PLACEHOLDER>" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:/https/ mcr.microsoft.com/dotnet/samples:aspnetapp
